# Commands to exeucte:
# cp ../paper/index.html static/paper/; cp ../paper/index.pdf static/paper/viridian.pdf

baseurl = "https://www.viridian-project.org/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = "true"

#theme = "hamburg"
theme = "hugo-theme-hamburg"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    siteLogo = "images/viridian_logo_with_text.png"
    themecolor = "#40826d" # Defines the tab color in Chrome for Android.
    # To load additional CSS styles
    customCSS = ['hamburg.css']
    # Show this very user-friendly and absolutely not annoying GDPR notice at the bottom of the page
    #ShowGDPRNotice = true
    #EnableHighlighting = true
    contact = true
    github = "viridian-project"

[languages]
    [languages.en]
        languageCode = "en"
        languageName = "English"
        title = "The Viridian Project"
        #subtitle = "A simple subtitle"
        # Copyright notice. This is displayer in the footer.
        copyright = "Copyright &copy; 2018-2020 Viridian Project"
        [languages.en.menu]
            [[languages.en.menu.main]]
                name = "Documents"
                identifier = "01-documents"
            [[languages.en.menu.main]]
                name = "Whitepaper"
                identifier = "02-whitepaper"
                parent = "01-documents"
                url = "../paper"
            [[languages.en.menu.main]]
                name = "Flyer"
                identifier = "03-flyer"
                parent = "01-documents"
                url = "flyer.pdf"
            [[languages.en.menu.main]]
                name = "Technical Paper"
                identifier = "04-technical"
                parent = "01-documents"
                url = "technical"
            [[languages.en.menu.main]]
                name = "About us"
                identifier = "05-about"
                url = "about"
            [[languages.en.menu.main]]
                name = "Contact"
                identifier = "06-contact"
                url = "contact"
        #[languages.en.params]
        #    siteLogo = "images/viridian_logo_with_text.png"
    [languages.de]
        languageCode = "de"
        languageName = "Deutsch"
        title = "Das Viridian-Projekt"
        #subtitle = "Ein einfacher Untertitel"
        copyright = "Copyright &copy; 2018-2020 Viridian Project"
        [languages.de.menu]
            [[languages.de.menu.main]]
                name = "Dokumente"
                identifier = "01-documents"
            [[languages.de.menu.main]]
                name = "Whitepaper (englisch)"
                identifier = "02-whitepaper"
                parent = "01-documents"
                url = "../paper"
            [[languages.de.menu.main]]
                name = "Flyer"
                identifier = "03-flyer"
                parent = "01-documents"
                url = "flyer.pdf"
            [[languages.de.menu.main]]
                name = "Technischer Artikel"
                identifier = "04-technical"
                parent = "01-documents"
                url = "technical"
            [[languages.de.menu.main]]
                name = "Über uns"
                identifier = "05-about"
                url = "about"
            [[languages.de.menu.main]]
                name = "Kontakt"
                identifier = "06-contact"
                url = "contact"
        #[languages.de.params]
        #    siteLogo = "images/viridian_logo_with_text.png"