---
title: "About the Viridian Project"
---

## Where did the idea for the Viridian project come from? {#first-section}

In November 2015, I was listening to a talk about [Transition Towns](https://transitionnetwork.org/),
which is a very cool idea to turn our economy into a sustainable, resilient,
local, post-fossil, fair economy. The Transition Towns concept stems from
an agricultural background and is basically the application of the
[principles of permaculture](https://permacultureprinciples.com/) to the entire economy.

The best about the Transition Town movement is its completely hands-on,
"just do it" attitude. Instead of waiting for a top-down system change to be
implemented by politics or big corporations or "someone else", it calls on
people to come together and start building things. It is this decentralized,
grass-roots nature of the movement that I like a lot.

Around the same time I was also reading a lot about bitcoin and cryptocurrencies
in general and started to grasp its vast potential for democratizing our economy
and financial system. After listening to the talk on Transition Towns, I was so
engaged by this encouraging just-do-it spirit that I was starting to think about
what I can do to contribute to this change. Because what I like most is IT and
computer programming, I was looking for something I could contribute from this
direction.

The Transition Town folks are mostly very low-tech gardening-savvy agricultural
people that like to get their hands dirty. But they also create new complementary
currencies that can even be paid digitially with a mobile phone. Yet, they did
not seem to have taken notice of cryptocurrencies, unaware of the decentralized
and democratic aspects of cryptocurrencies that actually align quite well with
the idea of a decentralized, resilient, grass-roots-based economy. I couldn't
stop thinking that something great could be born if these two communities, unaware
of each other, would be brought together.

Then I was by chance reading a novel that someone gave to me: [*Daemon*](https://en.wikipedia.org/wiki/Daemon_(novel_series)) and, much
more important, its sequel [*Freedom™*](https://en.wikipedia.org/wiki/Freedom%E2%84%A2)
by Daniel Suarez. While the first book describes how a decentralized computer
virus (the "Daemon") starts to take over the world, creating a dystopy full
of violence, in which skillful hackers turn into powerful tech-wizards ruling
the clueless crowd, the second book tells quite a different story. In Freedom™,
the reader learns that the violence of the Daemon has the purpose of breaking
the power of global corporations and elites, creating a new economy that consists
of many small communities (called hubs) that resiliently and sustainably produce
much of their demand for goods themselves, trading with other hubs for things
they cannot make themselves. There is an alternative currency ("credits", like
in a computer game) inside the Daemon network and sustainable solutions (e.g.
use of renewable energies) is rewarded with more credits by the Daemon network.

I was fascinated by the books, because what was described there was in essence
a kind of digitally-driven Transition Towns movement. A transition towards a
decentralized, resilient, sustainable, more equitable economy. This was exactly
what I was hoping to contribute to the Transition Towns movement!

I was a little surprised that in the Daemon novels, which mention many existing
innovative technologies, there was not a single mention of cryptocurrencies
(although the Daemon network is end-to-end encrypted, at least). But this is
simply owed to the Daemon novels being so "old" already. The first book was
released in 2006, the second book in January 2010. Satoshi Nakamoto,
the mysterious creator of bitcoin, released the first version of his
revolutionary cryptocurrency software in January 2009, and back in 2009, almost
no-one had ever heard of cryptocurrencies yet.


## Why is it called "Viridian"?

[Viridian](https://en.wikipedia.org/wiki/Viridian) is the name of a certain
greenish color, a dark shade of "spring green". It is derived from the Latin word
for green, *viridis*. Because the Viridian project is all about colors, and one
hopes for them to be rather green than anything else, I figured the name of a
green color would be appropriate. Besides, it also sounds pretty cool.


## Are there similar projects?

There are other projects that are related to the Viridian project. Some of them
are listed here:

* [FairCoin](https://fair-coin.org), by the FairCoop, claims to be the most
  ecological and resilient cryptocurrency, supporting ethical business values.
  The [FairCoop](https://fair.coop/) is a global network of communities that want
  to decentralize and localize the economy and replace capitalism with
  cooperativism.
* [CoinSence](http://coinsence.org/) wants to create a common platform for social
  collaboration, value creation, and a sustainable economy. Everyone can create
  a community on the open platform and every community can create its own
  social currency and finance projects with it. CoinSence wants to strengthen
  the civil society, empower social and ecological volunteer work, and support
  the development of a collaborative, fair, sustainable economy.

There could be opportunities to cooperate and benefit from synergies.
